### ISSUE TITLE
Panic at startup `iced_widget/src/scrollable.rs:1241:53`

### ISSUE THREAD

**Issue by nuke-web3** [pop-os/cosmic-store#220]
Using Cosmic alpha 4, I got a notification of system updates available, and tried to open the store to update, but cannot with:

```sh
$ cosmic-store

[2024-12-09T20:33:43Z WARN  wgpu_hal::gles::adapter] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
[2024-12-09T20:33:43Z WARN  wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
[2024-12-09T20:33:43Z WARN  sctk_adwaita::buttons] Ignoring unknown button type:
thread 'main' panicked at /build/cosmic-store-Stjxm2/cosmic-store-0.1.0~1733177868~22.04~9885eee/vendor/iced_widget/src/scrollable.rs:1241:53:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

A window manifests shortly then crashes on each attempt to open the store.

---

Updating via the Pop Shop:
```
8 components with updates:
 • cosmic-comp
	Wayland compositor of pop-os cosmic shell
	Version: 0.1~1733420229~22.04~7829e76
 • cosmic-player
	Cosmic Media Player
	Version: 0.1.0~1733431318~22.04~b26005d
 • cosmic-session
	The session for the COSMIC desktop
	Version: 0.1.0~1733496467~22.04~78316ba
 • gir1.2-javascriptcoregtk-4.0
	JavaScript engine library from WebKitGTK - GObject introspection data
	Version: 2.46.4-0ubuntu0.22.04.1
 • gir1.2-webkit2-4.0
	Web content engine library for GTK - GObject introspection data
	Version: 2.46.4-0ubuntu0.22.04.1
 • libjavascriptcoregtk-4.0-18
	JavaScript engine library from WebKitGTK
	Version: 2.46.4-0ubuntu0.22.04.1
 • libwebkit2gtk-4.0-37
	Web content engine library for GTK
	Version: 2.46.4-0ubuntu0.22.04.1
 • system76-firmware-daemon
	System76 Firmware Daemon
	Version: 1.0.64~1733435605~22.04~59c6643
```

Same behavior, but on first attempt the store window came up for a second or two before crashing.

**Comment by nuke-web3** [comment]
duplicate open #216
