### ISSUE TITLE
Cosmic store crashes on launch attempt

### ISSUE THREAD

**Issue by Raevyn13** [pop-os/cosmic-store#73]
I did see issue #71, but my errors were different. I do not know what it's asking me for, so I came here.

cosmic-store                                                                                       ~
[2024-05-15T16:24:28Z ERROR i18n_embed::fluent] Error while adding resource to bundle: Overriding { kind: Message, id: "utilities" }.
[2024-05-15T16:24:28Z ERROR i18n_embed::fluent] Error while adding resource to bundle: Overriding { kind: Message, id: "utilities" }.
[2024-05-15T16:24:29Z WARN  wgpu_hal::gles::egl] No config found!
[2024-05-15T16:24:29Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively
[2024-05-15T16:24:29Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-05-15T16:24:29Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-05-15T16:24:29Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
thread 'main' panicked at /build/cosmic-store-FpsAEw/cosmic-store-0.1.0~1714166022~22.04~225ebca/vendor/winit/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /build/cosmic-store-FpsAEw/cosmic-store-0.1.0~1714166022~22.04~225ebca/vendor/winit/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5af09b06e15b - <unknown>
   1:     0x5af09b0b49e0 - <unknown>
   2:     0x5af09b061abd - <unknown>
   3:     0x5af09b06df44 - <unknown>
   4:     0x5af09b09721a - <unknown>
   5:     0x5af09b096ebd - <unknown>
   6:     0x5af09b097638 - <unknown>
   7:     0x5af09b06e53e - <unknown>
   8:     0x5af09b06e376 - <unknown>
   9:     0x5af09b097362 - <unknown>
  10:     0x5af099fa5665 - <unknown>
  11:     0x5af099fa5e13 - <unknown>
  12:     0x5af09a75d203 - <unknown>
  13:     0x5af09a73aa6c - <unknown>
  14:     0x5af09a1ae5f4 - <unknown>
  15:     0x5af09a11402c - <unknown>
  16:     0x5af09a11fbc4 - <unknown>
  17:     0x5af09a1db899 - <unknown>
  18:     0x5af09a11a865 - <unknown>
  19:     0x5af09a06128e - <unknown>
  20:     0x5af09a21f013 - <unknown>
  21:     0x5af09a11dba9 - <unknown>
  22:     0x5af09b097254 - <unknown>
  23:     0x5af09b07d2eb - <unknown>
  24:     0x5af09a11db9e - <unknown>
  25:     0x774a1b629d90 - <unknown>
  26:     0x774a1b629e40 - __libc_start_main
  27:     0x5af099fa6245 - <unknown>
  28:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:144:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    508929 IOT instruction (core dumped)  cosmic-store

**Comment by emujoyce** [comment]
I may be getting similar issues
```
@pop-os:~$ RUST_BACKTRACE=full cosmic-store
[2024-06-24T23:29:31Z WARN  wgpu_hal::gles::egl] No windowing system present. Using surfaceless platform
[2024-06-24T23:29:31Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-24T23:29:31Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-24T23:29:31Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "136",
        error_code: 136,
        request_code: 148,
        minor_code: 1,
    }
[2024-06-24T23:29:32Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-24T23:29:33Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
...
```

I can no longer launch the cosmic store.

OS: Pop!_OS 22.04 LTS x86_64
Host: NUC11BTMi9 M26263-402 
Kernel: 6.9.3-76060903-generic
CPU: 11th Gen Intel i9-11900KB (16) @ 4.900GHz
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate

**Comment by Ultranique** [comment]
Same issue here:

[2024-06-30T14:17:54Z WARN  wgpu_hal::gles::egl] No windowing system present. Using surfaceless platform
[2024-06-30T14:17:54Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-30T14:17:54Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-30T14:17:54Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:54Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:54Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:55Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
X        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:55Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:55Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-30T14:17:55Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "136",
        error_code: 136,
        request_code: 148,
        minor_code: 1,
    }
[2024-06-30T14:17:56Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-30T14:17:57Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-30T14:17:58Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-30T14:17:59Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.

This is from a clean install of POP with no other software added.

System: POP_OS! LTS - 6.9.3-76060903-generic
ASRock X670E Taichi
RAM: 64GB DDR5 6000 (issue also happens at stock 4800)
CPU: Ryzen 7950X
GPU: RTX 4090

I have no issue with cosmic-store on other systems with Ryzen 5900x and Nvidia 3090, and all AMD GPU based systems I have tried so far also work.
