### ISSUE TITLE
Anki crashes when launched from COSMIC App Store

### ISSUE THREAD

**Issue by skmd0** [pop-os/cosmic-store#77]
## Bug Description

Anki application (flatpak) crashes when launched from COSMIC App Store. When I click the Open button, Anki launches and immediately crashes. This crash only happens when launching from COSMIC App Store.

![screenshot-2024-05-18-13-03-28](https://github.com/pop-os/cosmic-store/assets/52122032/d8e057b9-e24a-4438-a684-e803cea38f5d)

```
Anki 24.04.1 (ccd9ca1a)  
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.38

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 258, in wrapped_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "aqt.update", line 17, in do_check
  File "anki._backend_generated", line 1037, in check_for_update
  File "anki._backend", line 162, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }
```

## Steps to Reproduce

1. Open COSMIC App Store
2. Install Anki (flatpak version)
3. Click on `Open` button

## Workaround

Launch Anki from the application launcher instead of COSMIC App Store.

## Specs
- OS: `Pop!_OS 22.04 LTS x86_64`
- Kernel: `6.8.0-76060800daily20240311-generic`
- Desktop environment: `COSMIC`
- cosmic-session: `Version: 0.1.0~1713557836~22.04~54c0955`
- cosmic-store: `Version 0.1.0~1714166022~22.04~225ebca`

**Comment by WesfunOfficial** [comment]
What GPU are you using? That may assist in looking for a solution

**Comment by skmd0** [comment]
I have integrated AMD GPU

**Comment by PriceCZ** [comment]
I've had the same issue. Pop!_OS 24.04 LTS, intel integrated graphics. Rebooting the computer fixed the issue for me.
